import request from 'supertest';
import app from '../app';
import prisma from '../lib/prisma';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { SALVATION_MODULE_KEY, SALVATION_PERMISSIONS } from '../services/salvation';

const JWT_SECRET = process.env.JWT_SECRET || 'fallback-secret';

describe('Module 35: Salvation & New Believer Journey Module', () => {
  let tenantId: string;
  let adminToken: string;
  let adminUserId: string;
  let leaderMemberId: string;
  let memberId: string;
  let profileId: string;
  let reminderId: string;
  let serviceId: string;
  let funnelId: string;

  beforeAll(async () => {
    // ── Clean up related tables ──────────────────────────────
    await prisma.newBelieverReminder.deleteMany({});
    await prisma.newBelieverProfile.deleteMany({});
    await prisma.analyticsEvent.deleteMany({});
    await prisma.churchService.deleteMany({});
    await prisma.ministryFunnel.deleteMany({});
    await prisma.member.deleteMany({});
    await prisma.rolePermission.deleteMany({});
    await prisma.role.deleteMany({});
    await prisma.userRole.deleteMany({});
    await prisma.user.deleteMany({});
    await prisma.tenant.deleteMany({});

    // ── Tenant ──────────────────────────────────────────────
    const tenant = await prisma.tenant.create({
      data: { name: 'Harvest Church', subdomain: 'harvest-church', status: 'active' },
    });
    tenantId = tenant.id;

    await prisma.moduleDefinition.upsert({
      where: { key: SALVATION_MODULE_KEY },
      update: { name: 'Salvation & New Believer Journey', category: 'Discipleship', dependencies: '["member-crm"]' },
      create: {
        key: SALVATION_MODULE_KEY,
        name: 'Salvation & New Believer Journey',
        category: 'Discipleship',
        dependencies: '["member-crm"]',
      },
    });
    await prisma.tenantModule.upsert({
      where: { tenantId_moduleKey: { tenantId, moduleKey: SALVATION_MODULE_KEY } },
      update: { status: 'active' },
      create: { tenantId, moduleKey: SALVATION_MODULE_KEY, status: 'active', billingRule: 'free' },
    });

    // ── Admin Role & Permissions ───────────────────────────
    const permissionNames = ['member.update', 'member.read', 'tenant.settings', ...SALVATION_PERMISSIONS];
    const permissions = await Promise.all(permissionNames.map((name) => prisma.permission.upsert({
      where: { name },
      update: {},
      create: { name, description: `Autogenerated test permission for ${name}` },
    })));
    const adminRole = await prisma.role.create({ data: { tenantId, name: 'Admin', isCustom: false } });
    await prisma.rolePermission.createMany({
      data: permissions.map((p) => ({ roleId: adminRole.id, permissionId: p.id })),
    });

    // ── Admin User & Leader Member ─────────────────────────
    const passHash = await bcrypt.hash('password123', 12);
    const adminUser = await prisma.user.create({
      data: { tenantId, email: 'pastor@harvest.com', passwordHash: passHash },
    });
    adminUserId = adminUser.id;
    await prisma.userRole.create({ data: { userId: adminUser.id, roleId: adminRole.id } });
    adminToken = jwt.sign({ userId: adminUser.id, tenantId, email: adminUser.email }, JWT_SECRET);

    const leaderMember = await prisma.member.create({
      data: {
        tenantId,
        userId: adminUser.id,
        firstName: 'Barnabas',
        lastName: 'Leader',
        email: 'pastor@harvest.com',
        membershipStatus: 'leader',
      },
    });
    leaderMemberId = leaderMember.id;

    // ── Pre-existing Service and Funnel ─────────────────────
    const service = await prisma.churchService.create({
      data: {
        tenantId,
        title: 'Sunday Victory Service',
        serviceType: 'sunday',
        serviceDate: new Date(),
        salvationCount: 0,
        status: 'published',
      },
    });
    serviceId = service.id;

    const funnel = await prisma.ministryFunnel.create({
      data: {
        tenantId,
        name: 'Salvation Call Landing Page',
        slug: 'give-life-to-christ',
        type: 'salvation',
        isActive: true,
      },
    });
    funnelId = funnel.id;
  });

  describe('Salvation Response Intake & Profile Setup', () => {
    it('should register a new convert response publicly, creating Member and NewBelieverProfile', async () => {
      const res = await request(app)
        .post('/api/salvation-new-believer-journey/respond')
        .set('x-tenant-id', tenantId)
        .send({
          firstName: 'Timothy',
          lastName: 'Convert',
          email: 'timothy@convert.com',
          phone: '+1888222333',
          source: 'livestream',
          serviceId,
          funnelId,
          location: 'New York',
          preferredLanguage: 'en',
        });

      expect(res.status).toBe(201);
      expect(res.body.data.id).toBeDefined();
      expect(res.body.data.memberId).toBeDefined();
      expect(res.body.data.source).toBe('livestream');
      expect(res.body.data.serviceId).toBe(serviceId);
      expect(res.body.data.funnelId).toBe(funnelId);
      expect(res.body.data.cellId).toBe('cell-new-york');

      profileId = res.body.data.id;
      memberId = res.body.data.memberId;
    });

    it('should keep the legacy salvation route mounted for existing integrations', async () => {
      const res = await request(app)
        .post('/api/salvation/respond')
        .set('x-tenant-id', tenantId)
        .send({
          firstName: 'Timothy',
          lastName: 'Convert',
          email: 'timothy@convert.com',
          source: 'livestream',
        });

      expect(res.status).toBe(201);
      expect(res.body.data.memberId).toBe(memberId);
    });

    it('should block public responses when the module is not activated for a tenant', async () => {
      const inactiveTenant = await prisma.tenant.create({
        data: { name: 'Inactive Church', subdomain: 'inactive-salvation', status: 'active' },
      });

      const res = await request(app)
        .post('/api/salvation-new-believer-journey/respond')
        .set('x-tenant-id', inactiveTenant.id)
        .send({
          firstName: 'No',
          lastName: 'Entitlement',
          email: 'inactive@example.com',
          source: 'web',
        });

      expect(res.status).toBe(403);
      expect(res.body.error).toBe('Module not activated');
    });

    it('should increment the salvation count on the linked church service', async () => {
      const svc = await prisma.churchService.findUnique({
        where: { id: serviceId },
      });
      expect(svc!.salvationCount).toBe(1);
    });

    it('should record the salvation response in analytics', async () => {
      const count = await prisma.analyticsEvent.count({
        where: { tenantId, category: 'salvation', name: 'response', entityId: profileId },
      });
      expect(count).toBe(1);
    });

    it('should allow authenticated staff to fetch the new convert profile', async () => {
      const res = await request(app)
        .get(`/api/salvation/profiles/${memberId}`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
      expect(res.body.data.id).toBe(profileId);
      expect(res.body.data.member.firstName).toBe('Timothy');
      expect(res.body.data.assignedAgentId).toBe(leaderMemberId);
    });

    it('should allow authenticated staff to list tenant new believer profiles', async () => {
      const res = await request(app)
        .get('/api/salvation-new-believer-journey/profiles')
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
      expect(res.body.data).toHaveLength(1);
      expect(res.body.data[0].member.email).toBe('timothy@convert.com');
    });
  });

  describe('Onboarding Automations & Resource Recommendations', () => {
    it('should automatically trigger welcome letters, follow-up drip, LMS enrollment, and Bible reading plans', async () => {
      const res = await request(app)
        .get(`/api/salvation/profiles/${memberId}`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);

      expect(res.body.data.welcomeSentAt).toBeDefined();
      expect(res.body.data.followUpStartedAt).toBeDefined();
      expect(res.body.data.bibleReadingPlanStartedAt).toBeDefined();
      expect(res.body.data.lmsEnrolledAt).toBeDefined();
    });

    it('should fetch recommended new believer digital materials and guides', async () => {
      const res = await request(app)
        .get('/api/salvation/resources')
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
      expect(res.body.data).toHaveLength(2);
      expect(res.body.data[0].title).toBe('Free Digital Holy Bible');
      expect(res.body.data[1].title).toBe('Foundation School Student Guide');
    });
  });

  describe('Care Team Routing & Reminders', () => {
    it('should list scheduled pending reminders for the care agent', async () => {
      const res = await request(app)
        .get('/api/salvation/reminders')
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`)
        .query({ assignedAgentId: leaderMemberId });

      expect(res.status).toBe(200);
      expect(res.body.data).toHaveLength(2);
      expect(res.body.data[0].reminderType).toBe('day7');
      expect(res.body.data[1].reminderType).toBe('day30');
      reminderId = res.body.data[0].id;
    });

    it('should allow staff to complete a follow-up reminder check', async () => {
      const res = await request(app)
        .post(`/api/salvation/reminders/${reminderId}/complete`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ notes: 'Timothy is reading his bible daily and feels welcomed.' });

      expect(res.status).toBe(200);
      expect(res.body.data.status).toBe('completed');
      expect(res.body.data.notes).toBe('Timothy is reading his bible daily and feels welcomed.');
      expect(res.body.data.completedAt).toBeDefined();
    });
  });

  describe('Spiritual Milestones Checklist', () => {
    it('should allow staff to record water baptism details', async () => {
      const bDate = new Date();
      const res = await request(app)
        .patch(`/api/salvation/profiles/${profileId}/baptism`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ baptismDate: bDate });

      expect(res.status).toBe(200);
      expect(res.body.data.isBaptized).toBe(true);
      expect(res.body.data.baptismDate).toBeDefined();
    });

    it('should allow staff to update cell group and class completion milestones', async () => {
      // 1. Group membership
      let res = await request(app)
        .patch(`/api/salvation/profiles/${profileId}/milestones`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ milestone: 'joinedGroup', value: true });

      expect(res.status).toBe(200);
      expect(res.body.data.joinedGroup).toBe(true);

      // 2. Class completion (graduation)
      res = await request(app)
        .patch(`/api/salvation/profiles/${profileId}/milestones`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ milestone: 'finishedClass', value: true });

      expect(res.status).toBe(200);
      expect(res.body.data.finishedClass).toBe(true);
      expect(res.body.data.lmsCompletedAt).toBeDefined();
    });

    it('should allow staff to assign a care agent through the API', async () => {
      const res = await request(app)
        .patch(`/api/salvation-new-believer-journey/profiles/${profileId}/assign-agent`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ assignedAgentId: leaderMemberId });

      expect(res.status).toBe(200);
      expect(res.body.data.assignedAgentId).toBe(leaderMemberId);
      expect(res.body.data.assignedAgent.firstName).toBe('Barnabas');
    });
  });

  describe('Canonical Developer API CRUD', () => {
    it('should create, list, read, update, and delete journey records from the root endpoint', async () => {
      const createRes = await request(app)
        .post('/api/salvation-new-believer-journey')
        .set('x-tenant-id', tenantId)
        .send({
          firstName: 'Api',
          lastName: 'Convert',
          email: 'api.convert@example.com',
          source: 'web',
        });

      expect(createRes.status).toBe(201);
      const tempProfileId = createRes.body.data.id;

      const listRes = await request(app)
        .get('/api/salvation-new-believer-journey')
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);
      expect(listRes.status).toBe(200);
      expect(listRes.body.data.some((item: any) => item.id === tempProfileId)).toBe(true);

      const readRes = await request(app)
        .get(`/api/salvation-new-believer-journey/${tempProfileId}`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);
      expect(readRes.status).toBe(200);
      expect(readRes.body.data.member.email).toBe('api.convert@example.com');

      const patchRes = await request(app)
        .patch(`/api/salvation-new-believer-journey/${tempProfileId}`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`)
        .send({ joinedGroup: true });
      expect(patchRes.status).toBe(200);
      expect(patchRes.body.data.joinedGroup).toBe(true);

      const deleteRes = await request(app)
        .delete(`/api/salvation-new-believer-journey/${tempProfileId}`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);
      expect(deleteRes.status).toBe(200);

      const afterDelete = await request(app)
        .get(`/api/salvation-new-believer-journey/${tempProfileId}`)
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);
      expect(afterDelete.status).toBe(404);
    });
  });

  describe('Analytics & Completion Reports', () => {
    it('should compile new believer journey progress metrics for pastors', async () => {
      const res = await request(app)
        .get('/api/salvation/reports/completion')
        .set('x-tenant-id', tenantId)
        .set('Authorization', `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
      expect(res.body.data.totalConverts).toBe(1);
      expect(res.body.data.welcomedCount).toBe(1);
      expect(res.body.data.lmsEnrolled).toBe(1);
      expect(res.body.data.lmsCompleted).toBe(1);
      expect(res.body.data.baptized).toBe(1);
      expect(res.body.data.joinedGroup).toBe(1);
      expect(res.body.data.finishedClass).toBe(1);
      expect(res.body.data.lmsCompletionRate).toBe(100);
      expect(res.body.data.baptismRate).toBe(100);
      expect(res.body.data.bySource[0].source).toBe('livestream');
      expect(res.body.data.bySource[0].count).toBe(1);
    });
  });
});
